---

- name: Removing hosts entries < 1.3.0
  lineinfile:
    state: absent
    dest: /etc/hosts
    regexp: "^.*# ansible$"

- name: Adding hosts entries
  blockinfile:
    path: /etc/hosts
    block: |
      {% for item in hosts_entries %}
      {{ item.ip }} {{ item.domain }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK weareinteractive.hosts"
